apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: explorer
  name: blockchain-explorer-app
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: explorer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: explorer
    spec:
      containers:
      - command:
        - sh
        - -c
        - /fabric/config/explorer/app/run.sh
        env:
        - name: TZ
          value: America/Sao_Paulo
        - name: DATABASE_HOST
          value: blockchain-explorer-db
        - name: DATABASE_USERNAME
          value: hppoc
        - name: DATABASE_PASSWORD
          value: password
        image: hyperledger/explorer:latest
        imagePullPolicy: Always
        name: explorer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc
status: {}
