apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: blockchain-org2peer1
  name: blockchain-org2peer1
spec:
  ports:
  - name: grpc
    port: 30110
    protocol: TCP
    targetPort: 30110
  - name: events
    port: 30111
    protocol: TCP
    targetPort: 30111
  - name: couchdb
    port: 5984
    protocol: TCP
    targetPort: 5984
  selector:
    name: org2peer1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
