apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: explorer-db
  name: blockchain-explorer-db
spec:
  ports:
  - name: pgsql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: explorer-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
