apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: blockchain-orderer
  name: blockchain-orderer
spec:
  ports:
  - name: grpc
    port: 31010
    protocol: TCP
    targetPort: 31010
  selector:
    name: orderer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
