apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: blockchain-ca
  name: blockchain-ca
spec:
  ports:
  - name: grpc
    port: 30054
    protocol: TCP
    targetPort: 7054
  - name: grpc1
    port: 7054
    protocol: TCP
    targetPort: 7054
  selector:
    name: ca
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
