apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: fabric-tools
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 48h
    env:
    - name: TZ
      value: America/Sao_Paulo
    - name: FABRIC_CFG_PATH
      value: /fabric
    image: hyperledger/fabric-tools:amd64-1.3.0
    imagePullPolicy: Always
    name: fabrictools
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /fabric
      name: fabricfiles
    - mountPath: /host/var/run/docker.sock
      name: dockersocket
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  volumes:
  - name: fabricfiles
    persistentVolumeClaim:
      claimName: fabric-pvc
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: dockersocket
status: {}
