apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    name: fabricfiles
    type: local
  name: fabric-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /nfs/fabric
    server: storage.local.parisi.biz
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Pending
